name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: self-hosted  # This ensures the job runs on your VPS

    steps:
      - name: Start SSH Agent
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Verify SSH Connection
        run: ssh -T git@github.com || true

      - name: Checkout Latest Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fetch and Pull Latest Code
        run: |
          git fetch --all
          git reset --hard origin/main  # Ensures latest changes
          git pull origin main  # Change 'main' if using another branch

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Restart Application (PM2)
        run: |
          pm2 stop taxation-app || true  # Stop if already running
          pm2 start src/server.js --name taxation-app
          pm2 save
          pm2 restart taxation-app  # Ensures updated code is used
